In [1]:
 import torch, torchvision, torchaudio
 print(torch.__version__)
 print(torchvision.__version__)
 print(torchaudio.__version__)

2.5.1
0.20.1
2.5.1


In [2]:
heights = [189, 170, 189, 163, 183, 171, 185,
           168, 173, 183, 173, 173, 175, 178,
           183, 193, 178, 173, 174, 183, 183,
           180, 168, 180, 170, 178, 182, 180,
           183, 178, 182, 188, 175, 179, 183,
           193, 182, 183, 177, 185, 188, 188,
           182, 185, 191, 183]

In [3]:
import torch
heights_tensor = torch.tensor(heights,    
           dtype=torch.float64)

In [4]:
heights_tensor

tensor([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173., 173.,
        175., 178., 183., 193., 178., 173., 174., 183., 183., 180., 168., 180.,
        170., 178., 182., 180., 183., 178., 182., 188., 175., 179., 183., 193.,
        182., 183., 177., 185., 188., 188., 182., 185., 191., 183.],
       dtype=torch.float64)

In [6]:
t1=torch.IntTensor([1, 2, 3])
t1

tensor([1, 2, 3], dtype=torch.int32)

In [7]:
t2=torch.tensor([1, 2, 3],
             dtype=torch.int)
t2

tensor([1, 2, 3], dtype=torch.int32)

In [8]:
t1 = torch.DoubleTensor([5,8,10])
t1

tensor([ 5.,  8., 10.], dtype=torch.float64)

In [9]:
t2 = torch.tensor([5,8,10], dtype= torch.float64)
t2

tensor([ 5.,  8., 10.], dtype=torch.float64)

In [10]:
tensor1 = torch.zeros(2, 3)
print(tensor1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
tensor2 = torch.ones(1,4,5)
print(tensor2)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [12]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
import numpy as np
nparr=np.array(range(10))
pt_tensor=torch.tensor(nparr, dtype=torch.int)
print(pt_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


In [14]:
height = heights_tensor[2]
print(height)

tensor(189., dtype=torch.float64)


In [15]:
height = heights_tensor[-2]
print(height)

tensor(191., dtype=torch.float64)


In [16]:
five_heights = heights_tensor[-5:]
print(five_heights)

tensor([188., 182., 185., 191., 183.], dtype=torch.float64)


In [17]:
heights_tensor[:5]

tensor([189., 170., 189., 163., 183.], dtype=torch.float64)

In [18]:
print(heights_tensor.shape)

torch.Size([46])


In [19]:
heights_in_feet = heights_tensor / 30.48
print(heights_in_feet)

tensor([6.2008, 5.5774, 6.2008, 5.3478, 6.0039, 5.6102, 6.0696, 5.5118, 5.6759,
        6.0039, 5.6759, 5.6759, 5.7415, 5.8399, 6.0039, 6.3320, 5.8399, 5.6759,
        5.7087, 6.0039, 6.0039, 5.9055, 5.5118, 5.9055, 5.5774, 5.8399, 5.9711,
        5.9055, 6.0039, 5.8399, 5.9711, 6.1680, 5.7415, 5.8727, 6.0039, 6.3320,
        5.9711, 6.0039, 5.8071, 6.0696, 6.1680, 6.1680, 5.9711, 6.0696, 6.2664,
        6.0039], dtype=torch.float64)


In [20]:
heights_2_measures = torch.cat(
    [heights_tensor,heights_in_feet], dim=0)
print(heights_2_measures.shape)

torch.Size([92])


In [21]:
heights_2_measures

tensor([189.0000, 170.0000, 189.0000, 163.0000, 183.0000, 171.0000, 185.0000,
        168.0000, 173.0000, 183.0000, 173.0000, 173.0000, 175.0000, 178.0000,
        183.0000, 193.0000, 178.0000, 173.0000, 174.0000, 183.0000, 183.0000,
        180.0000, 168.0000, 180.0000, 170.0000, 178.0000, 182.0000, 180.0000,
        183.0000, 178.0000, 182.0000, 188.0000, 175.0000, 179.0000, 183.0000,
        193.0000, 182.0000, 183.0000, 177.0000, 185.0000, 188.0000, 188.0000,
        182.0000, 185.0000, 191.0000, 183.0000,   6.2008,   5.5774,   6.2008,
          5.3478,   6.0039,   5.6102,   6.0696,   5.5118,   5.6759,   6.0039,
          5.6759,   5.6759,   5.7415,   5.8399,   6.0039,   6.3320,   5.8399,
          5.6759,   5.7087,   6.0039,   6.0039,   5.9055,   5.5118,   5.9055,
          5.5774,   5.8399,   5.9711,   5.9055,   6.0039,   5.8399,   5.9711,
          6.1680,   5.7415,   5.8727,   6.0039,   6.3320,   5.9711,   6.0039,
          5.8071,   6.0696,   6.1680,   6.1680,   5.9711,   6.06

In [22]:
 heights_reshaped = heights_2_measures.reshape(2, 46)

In [23]:
heights_reshaped

tensor([[189.0000, 170.0000, 189.0000, 163.0000, 183.0000, 171.0000, 185.0000,
         168.0000, 173.0000, 183.0000, 173.0000, 173.0000, 175.0000, 178.0000,
         183.0000, 193.0000, 178.0000, 173.0000, 174.0000, 183.0000, 183.0000,
         180.0000, 168.0000, 180.0000, 170.0000, 178.0000, 182.0000, 180.0000,
         183.0000, 178.0000, 182.0000, 188.0000, 175.0000, 179.0000, 183.0000,
         193.0000, 182.0000, 183.0000, 177.0000, 185.0000, 188.0000, 188.0000,
         182.0000, 185.0000, 191.0000, 183.0000],
        [  6.2008,   5.5774,   6.2008,   5.3478,   6.0039,   5.6102,   6.0696,
           5.5118,   5.6759,   6.0039,   5.6759,   5.6759,   5.7415,   5.8399,
           6.0039,   6.3320,   5.8399,   5.6759,   5.7087,   6.0039,   6.0039,
           5.9055,   5.5118,   5.9055,   5.5774,   5.8399,   5.9711,   5.9055,
           6.0039,   5.8399,   5.9711,   6.1680,   5.7415,   5.8727,   6.0039,
           6.3320,   5.9711,   6.0039,   5.8071,   6.0696,   6.1680,   6.1680,
  

In [24]:
print(heights_reshaped[1,-2])

tensor(6.2664, dtype=torch.float64)


In [25]:
print(heights_reshaped[0,-1])

tensor(183., dtype=torch.float64)
